package com.ksh2.crypt;

/*
  ErrorDialog.java

 */



public class MessageDialog extends javax.swing.JDialog {

    /** Creates new form ErrorDialog */
    public MessageDialog(java.awt.Frame parent,boolean modal) {
        super (parent, modal);
        initComponents ();
        pack ();
        this.setSize(400,120);
    }
    
    public MessageDialog(java.awt.Dialog parent, boolean modal){
       super (parent, modal);
        initComponents ();
        pack ();
        this.setSize(330,120);
    }
    public MessageDialog() {
        super ();
        initComponents ();
        pack ();
        this.setSize(330,120);
    }
        

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        message = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        getContentPane().setLayout(new java.awt.FlowLayout());
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        }
        );
        
        message.setText("The Two Passwords Are Not The Same!!!");
        message.setFont(new java.awt.Font ("Dialog", 0, 14));
        
        getContentPane().add(message);
        
        
        okButton.setFont(new java.awt.Font ("Dialog", 0, 18));
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        }
        );
        
        getContentPane().add(okButton);
        
    }//GEN-END:initComponents

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
// Add your handling code here:
       setVisible (false);
        dispose ();

  }//GEN-LAST:event_okButtonActionPerformed
  public void setDialogLabel(String str){
      message.setText(str);
  }
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible (false);
        dispose ();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        new MessageDialog (new javax.swing.JFrame (), true).show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel message;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

}
